config/routes.rb
Rails.application.routes.draw do
  get 'favorite_posts/create'

  get 'favorite_posts/destroy'

  post 'likes/vote'

  post 'comments/new'
  get 'comments/new'

  post 'comments/create'
  get 'comments/create'

  post 'comments/update'
  get 'comments/update'

  post 'comments/edit'
  get 'comments/edit'

  resources :users do
    resources :favorite_posts
    resources :posts
  end
  resources :sessions
  resources :posts do
    resources :comments
    resources :favorite_posts, only: [:create, :destroy]
    member do
      post 'vote'
    end
  end

  root 'posts#index'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body,
            length: { minimum: 1, maximum: 500 },
            presence: true

  belongs_to :post
  belongs_to :user

  has_ancestry
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_comment_permission, only: :destroy
  before_action :set_comment, only: [:update, :destroy, :edit]
  before_action :set_post

  def index
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = session[:user_id]
    if @comment.depth >= 5
      @comment.ancestry = nil
    end
    @post.touch
    if @comment.save
      current_user.update_attribute('raiting', current_user.raiting += 2)

      respond_to do |format|
        format.html { redirect_to @post, notice: 'Your comment was sent' }
        format.js {}
      end

    else
      flash.now[:danger] = 'error'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    current_user.update_attribute('raiting', current_user.raiting -= 2)
    respond_to do |format|
      format.html { redirect_to @post, notice: 'The comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js { }
    end

  end

  def update
    respond_to do |format|
      if @comment.update(params.require(:comment).permit(:body))
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.js {}
      else
        format.html { redirect_to @post, notice: 'Error' }
        format.js {}
      end
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    respond_to do |format|
      format.html { redirect_to @post, notice: 'The comment was successfully updated.' }
      format.js {}
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end

  def check_comment_permission
    @comment = Comment.find(params[:id])
    unless @comment.user.id == session[:user_id]
      flash[:alert] = 'You have not permission!'
      redirect_to @comment.post
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
table class='comment' id=comment.id
  tr
    td
      = gravatar_for(comment.user)
    td
      h4 = link_to comment.user.name, comment.user
      div.comment_body = comment.body
      div.comment_info.text-muted
        =' distance_of_time_in_words(comment.created_at, Time.now) + ' ago'

        - unless comment.root?
          = ' to ' + comment.parent.user.name + ' '

        - if comment.depth < 4 and current_user
          span' -
          =' link_to ' Reply', new_post_comment_path(post_id: comment.post.id, parent_id: comment.id), remote: true, method: :get
        - if check_user_comment(comment)
          | -
          - if comment_time(comment) < 300
            = link_to 'Edit', edit_post_comment_path(@post, comment), remote: true
          | -
          =' link_to ' Destroy', post_comment_path(@post, comment), method: :delete, data: {confirm: 'Are you sure?'}, remote: true,
          class: 'text-danger'
    tr
      td
      td.comment-children
        - if comment.has_children?
          - comment.children.each do |child_comment|
            = render partial: 'comments/comment', locals: { comment: child_comment }

app/views/comments/_form.html.slim
= form_for [@post, @comment], remote: true do |c|

  = c.hidden_field :parent_id, value: params[:parent_id] ? params[:parent_id] : nil

  div.field
    = c.label 'New comment'
    br
    = c.text_area :body

  div.actions
    = c.submit

app/views/comments/_test.html.slim
= form_for [@post, @comment]do |c|
  div.field
    = c.label :body
    br
    = c.text_area :body

  div.actions
    = c.submit

app/views/comments/create.js.erb
$('.new_comment textarea').val('');

<% if @comment.root? %>
  $(".comments_box").append("<%= escape_javascript render(:partial => 'comments/comment', :locals => { :comment => @comment }) %>");
<% else %>
  $("#<%= @comment.parent.id %> > tbody > tr > .comment-children ").append("<%= escape_javascript render(:partial => 'comments/comment', :locals => { :comment => @comment }) %>");
<% end %>3

app/views/comments/destroy.js.erb
$('#new_comment').remove();
$('.new_comment_btn').css('display', 'inline-block');
$('#<%= @comment.id %>').css('background-color', 'rgba(255,0,0,0.3)').fadeOut( "slow", function() {
  $('#<%= @comment.id %>').remove();
});

app/views/comments/edit.js.erb
$('#new_comment').remove();
$('.edit_comment').remove();
$('.comment_body').css('display', 'block')
$(".new_comment_btn").css('display', 'inline-block')
$('#<%= @comment.id %> > tbody > tr > td > .comment_body').css('display', 'none').after('<%= j render(:partial => 'comments/form') %>');

app/views/comments/new.html.slim
h1 New comment

= form_for [:post, @comment] do |c|
  div.field
    = c.label :body
    br
    = c.text_area :body

  div.actions
    = c.submit

app/views/comments/new.js.erb
$('#new_comment').remove();

var display = $('.edit_comment').css('display')

if ($('.edit_comment').css('display') === 'block'){
  $('.edit_comment').remove();
  $('.comment_body').css('display', 'block');
}

<% if params[:parent_id].nil? %>
  $(".comments").append("<%= j render(:partial => 'comments/form') %>");
  $(".new_comment_btn").css('display', 'none')
<% else %>
  $('#<%= params[:parent_id] %>').after('<%= j render(:partial => 'comments/form') %>');
  $(".new_comment_btn").css('display', 'inline-block')
<% end %>

app/views/comments/update.js.erb
$('#<%= @comment.id %>').html('<%= j render(:partial => 'comments/comment', locals: {:comment => @comment}) %>');