config/routes.rb
Rails.application.routes.draw do
  get 'favorite_posts/create'

  get 'favorite_posts/destroy'

  post 'likes/vote'

  post 'comments/new'
  get 'comments/new'

  post 'comments/create'
  get 'comments/create'

  post 'comments/update'
  get 'comments/update'

  post 'comments/edit'
  get 'comments/edit'

  resources :users do
    resources :favorite_posts
    resources :posts
  end
  resources :sessions
  resources :posts do
    resources :comments
    resources :favorite_posts, only: [:create, :destroy]
    member do
      post 'vote'
    end
  end

  root 'posts#index'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :favorites
  has_many :favorite_posts, through: :favorites, source: :favorited, source_type: 'Post'

  def to_param
    [id, name].join("-")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @user_posts = Post.where(user_id: @user.id)
    @user_favorites = @user.favorite_posts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Green App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all.order(:raiting).reverse
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def check_user_permission
    if current_user.present?
      ( @user.id == current_user.id) ? true : false
    end
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/index.html.slim
div
  h1 Users
  table.table-responsive.users
    thead
      tr
        th Id
        th Name
        th e-mail
        th Raiting
        th Registered

    - @users.each do |user|
      tbody
        tr
          td = user.id
          td = link_to user.name, user
          td = user.email
          td = user.raiting
          td = user.created_at.to_date

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.slim
div.user-page
  h1 Profile
  table
    tr
      td = gravatar_for @user
      td.user-info
        p
          i' class="fa fa-user"
          = @user.name
        p
          i' class="fa fa-envelope"
          span = @user.email
        p
          = image_tag 'http://findicons.com/files/icons/1620/crystal_project/128/keditbookmarks.png', class: 'star'
          = link_to 'Favorite posts', user_favorite_posts_url(user_id: @user.id)
          = image_tag 'http://findicons.com/files/icons/1620/crystal_project/128/keditbookmarks.png', class: 'star'

    tr
      td.text-center
        | Rating:
        = @user.raiting


      td.likes_count
        = image_tag 'thumbs-up.png', :style => 'top: -3px'
        = @user.likes.where(like_post: true).count

        = image_tag 'thumbs-down.png'
        = @user.likes.where(dislike_post: true).count
  h3 User posts:
  table.table.table-striped
    thead
      tr
      th Title
      th Content
      th Tags
      th Likes
      th Dislikes
      th Date
      th
    tbody
      - @user_posts.each do |post|
        tr
          td = post.title
          td = post.body.truncate(30)
          td = raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
          td.text-center = post.likes.like_post.count
          td.text-center = post.likes.dislike_post.count
          td style='min-width: 100px' = post.created_at.to_date
          td style = 'min-width: 220px'
            = link_to 'Show', post, class: 'btn btn-info'
            - if session[:user_id] == @user.id
              = link_to 'Edit', edit_post_path(post), class: 'btn btn-warning'
              = link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'