config/routes.rb
Rails.application.routes.draw do
  get 'favorite_posts/create'

  get 'favorite_posts/destroy'

  post 'likes/vote'

  post 'comments/new'
  get 'comments/new'

  post 'comments/create'
  get 'comments/create'

  post 'comments/update'
  get 'comments/update'

  post 'comments/edit'
  get 'comments/edit'

  resources :users do
    resources :favorite_posts
    resources :posts
  end
  resources :sessions
  resources :posts do
    resources :comments
    resources :favorite_posts, only: [:create, :destroy]
    member do
      post 'vote'
    end
  end

  root 'posts#index'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable

  validates_presence_of :title, :body, :user_id
  validates :title,
            length: { minimum: 5, maximum: 140 },
            uniqueness: true
  validates :body, length: { minimum: 140 }

  belongs_to  :user
  has_many    :comments, dependent: :destroy
  has_many    :likes, dependent: :destroy

  scope :newest, -> { order('created_at')  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :check_user_auth, only: :create

  attr_accessor :raiting

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    if params[:search].present?
      @posts = Post.where('title LIKE ? or body LIKE ? or tags LIKE ?',
                          "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    elsif params['sort_by'] == 'popular'
      @posts = @posts.sort_by { |post| post.likes.like_post.count}.reverse
    elsif params['sort_by'] == 'active'
      @posts = @posts.sort_by { |post| post[:updated_at]}.reverse
    elsif params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all.newest.reverse
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.where(ancestry: nil)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
    if session[:user_id].nil?
      redirect_to login_path
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        current_user.update_attribute('raiting', current_user.raiting += 5)
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    current_user.update_attribute('raiting', current_user.raiting -= 5)
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list, :post_image_url)
    end

    def check_user
      if @post.user_id != session[:user_id]
        flash[:alert] = 'You have not permission!'
        redirect_to root_path
      end
    end

    def check_user_auth
      if session[:user_id].nil?
        flash[:alert] = 'You have not permission!'
        redirect_to root_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def check_user_post
    true if @post.user.id == session[:user_id]
  end

  def check_user_comment(comment)
    true if comment[:user_id] == session[:user_id]
  end

  def comments_count post
    if post.comments.count == 1
      post.comments.count.to_s + ' comment'
    else
      post.comments.count.to_s + ' comments'
    end
  end

end

app/views/posts/_form.html.slim
= form_for(@post) do |f|
  -if @post.errors.any?
    div#error_explanation
      h2
        = pluralize(@post.errors.count, "error")
          | prohibited this post from being saved:
      ul
        - @post.errors.full_messages.each do |message|
          li
            = message

  div.field
    = f.label :title
    br
    = f.text_field :title

  div.field
    = f.label :post_image_url, 'Image URL (can be blank)'
    br
    = f.text_field :post_image_url

  div.field
    = f.label :body
    br
    = f.text_area :body

  div.field
    = f.label :tag_list, 'Tags (separated by commas)'
    br
    = f.text_field :tag_list

  div.actions
    = f.submit

app/views/posts/edit.html.slim
h1 Editing Post

= render 'form'

= link_to 'Show', @post, class: 'btn btn-info'

= link_to 'Back', posts_path, class: 'btn btn-default'

app/views/posts/index.html.slim
h1 Listing Posts

div.posts-actions
  = link_to 'New Post', new_post_path, class: 'btn btn-success', style: 'margin-bottom: 20px'

  //= link_to 'Popular posts', controller: :posts, action: :index, :method => 'get', popular: :true
  span Sort:
  = form_tag posts_path, class: 'sort', :method => 'get' do
    = select_tag(:sort_by, options_for_select([['Newest', 'newest'], ['Popular', 'popular'], ['Active', 'active']], params[:sort_by]), :onchange => "this.form.submit();")



  = form_tag posts_path,:class => 'navbar-right search', :method => 'get' do
    p
      = text_field_tag :search, params[:search]
      = button_tag :submit, :name => nil
        =image_tag 'http://iconizer.net/files/Brightmix/orig/monotone_search_zoom.png'

- @posts.each do |post|
  table.post
    tr
      td.user-in-post
        = gravatar_for post.user
        =' link_to post.user.name, post.user
      td.post-content
        h4
          = link_to post.title, post

        div.post-image-preview
          = image_tag post.post_image_url

        p
          = post.body

        div.tags.text-muted
          | Tags:
          = raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')

        div.post-info
          div
            = post.created_at.to_date
          div.votes
            - @post = post
            = render partial: ('likes/like')
            = render partial: ('likes/dislike')

          =' link_to comments_count(post), post_path(post, anchor: 'comments'), class: 'count_comments'

br


= link_to 'New Post', new_post_path, class: 'btn btn-success'

app/views/posts/new.html.slim
h1 New Post

= render 'form'

= link_to 'Back', posts_path, class: 'btn btn-default'

app/views/posts/show.html.slim
div.post


  div.post-image
    = image_tag @post.post_image_url

  h2.title
    = @post.title
    
  div.votes
    = render partial: ('likes/like')
    = render partial: ('likes/dislike')

  div.favorites
    -if current_user.present?
      - unless current_user.favorite_posts.exists?(id: @post.id)
        = link_to ' ', post_favorite_posts_path(post_id: @post.id), method: :post, class: 'favorite'
      - else
        = link_to ' ', post_favorite_post_path(post_id: @post.id), method: :delete, class: 'unfavorite'

  p.body
    = @post.body

  p.tags.text-muted
    | Tags:&nbsp;
    = raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')

  div.post-info
    div
      = @post.created_at
    | Author:&nbsp;
    =' link_to @post.user.name, @post.user


  div.actions
    = link_to 'Back', :back, class: 'btn  btn-default'
    - if current_user == @post.user
      = link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning'
      = link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger'

div.comments#comments
  h3 Comments
  div.comments_box
    - @comments.each do |comment|
      = render partial: 'comments/comment', locals: { comment: comment }

  -if @current_user.present?
    =' link_to 'New comment', new_post_comment_path(post_id: @post.id, parent_id: nil), remote: true, method: :get,
    class: 'btn btn-success new_comment_btn'
    = render partial: 'comments/form'

  -else
    p Только авторизированные пользователи могут оставлять комментарии
    = link_to 'Log in', login_path, class: 'btn btn-success'