config/routes.rb
Rails.application.routes.draw do
  get 'favorite_posts/create'

  get 'favorite_posts/destroy'

  post 'likes/vote'

  post 'comments/new'
  get 'comments/new'

  post 'comments/create'
  get 'comments/create'

  post 'comments/update'
  get 'comments/update'

  post 'comments/edit'
  get 'comments/edit'

  resources :users do
    resources :favorite_posts
    resources :posts
  end
  resources :sessions
  resources :posts do
    resources :comments
    resources :favorite_posts, only: [:create, :destroy]
    member do
      post 'vote'
    end
  end

  root 'posts#index'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Green Blog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Posts", root_path %></li>
        <% if !logged_in? %>
            <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRLesson3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <% if session[:count] == 10 %>
          <%= render 'shared/modal_banner'%>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>